###############################################################################
# Services for development only
# IMPORTANT!!! Data is wiped on provision
###############################################################################

version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0.6-ubi9
    container_name: mongodb
    network_mode: host
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=localhost
    volumes:
      - ./resources/database/seed.js:/docker-entrypoint-initdb.d/seed.js:ro

volumes:
  postgres_data:
