name: RELEASE

# Run this workflow when deploy is successful
on:
  workflow_dispatch:

# This ensures that no matter what triggers this workflow (a push, a manual trigger, etc.),
# only one instance of it will ever run at a time across your entire repository.
concurrency:
  # Use the workflow's name as the unique lock.
  # All runs of this workflow will share the same concurrency group.
  group: ${{ github.workflow }}
  # If a new run is triggered, wait for the existing one to finish.
  cancel-in-progress: true

# Downloads the Render CLI binary and adds it to the PATH.
# To prevent breaking changes in CI/CD, we pin to a
# specific CLI version (in this case 1.1.0).

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Make script executable
        run: chmod +x scripts/release.sh
      - name: Install release toolchain
        run: sudo apt install -qqq -y jq unzip
      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v1.1.0/cli_1.1.0_linux_amd64.zip -o render.zip
          unzip render.zip -d /tmp
          sudo mv /tmp/cli_v1.1.0 /usr/local/bin/render
      - name: Trigger deploy with Render CLI
        env:
          # The CLI can authenticate via a Render API key without logging in.
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          CI: true
        run: ./scripts/release.sh
